package com.drew.metadata.exif;

import android.support.media.ExifInterface;
import com.drew.metadata.Directory;
import java.util.HashMap;

public abstract class ExifDirectoryBase extends Directory {
    public static final int A = 282;
    public static final int B = 283;
    public static final int C = 284;
    public static final int D = 285;
    public static final int E = 296;
    public static final int F = 297;
    public static final int G = 301;
    public static final int H = 305;
    public static final int I = 306;
    public static final int J = 315;
    public static final int K = 316;
    public static final int L = 317;
    public static final int M = 318;
    public static final int N = 319;
    public static final int O = 322;
    public static final int P = 323;
    public static final int Q = 324;
    public static final int R = 325;
    public static final int S = 330;
    public static final int T = 342;
    public static final int U = 347;
    public static final int V = 512;
    public static final int W = 515;
    public static final int X = 517;
    public static final int Y = 518;
    public static final int Z = 519;
    public static final int aA = 34859;
    public static final int aB = 34864;
    public static final int aC = 34865;
    public static final int aD = 34866;
    public static final int aE = 34858;
    public static final int aF = 34859;
    public static final int aG = 36864;
    public static final int aH = 36867;
    public static final int aI = 36868;
    public static final int aJ = 37121;
    public static final int aK = 37122;
    public static final int aL = 37377;
    public static final int aM = 37378;
    public static final int aN = 37379;
    public static final int aO = 37380;
    public static final int aP = 37381;
    public static final int aQ = 37382;
    public static final int aR = 37383;
    @Deprecated
    public static final int aS = 37384;
    public static final int aT = 37384;
    public static final int aU = 37385;
    public static final int aV = 37386;
    public static final int aW = 37387;
    public static final int aX = 37388;
    public static final int aY = 37389;
    public static final int aZ = 37390;
    public static final int aa = 520;
    public static final int ab = 521;
    public static final int ac = 529;
    public static final int ad = 530;
    public static final int ae = 531;
    public static final int af = 532;
    public static final int ag = 559;
    public static final int ah = 700;
    public static final int ai = 4096;
    public static final int aj = 4097;
    public static final int ak = 4098;
    public static final int al = 18246;
    public static final int am = 33421;
    public static final int an = 33422;
    public static final int ao = 33423;
    public static final int ap = 33432;
    public static final int aq = 33434;
    public static final int ar = 33437;
    public static final int as = 33723;
    public static final int at = 34675;
    public static final int au = 34850;
    public static final int av = 34852;
    public static final int aw = 34855;
    public static final int ax = 34856;
    public static final int ay = 34857;
    public static final int az = 34858;
    public static final int bA = 41488;
    public static final int bB = 41492;
    public static final int bC = 41493;
    public static final int bD = 41495;
    public static final int bE = 41728;
    public static final int bF = 41729;
    public static final int bG = 41730;
    public static final int bH = 41985;
    public static final int bI = 41986;
    public static final int bJ = 41987;
    public static final int bK = 41988;
    public static final int bL = 41989;
    public static final int bM = 41990;
    public static final int bN = 41991;
    public static final int bO = 41992;
    public static final int bP = 41993;
    public static final int bQ = 41994;
    public static final int bR = 41995;
    public static final int bS = 41996;
    public static final int bT = 42016;
    public static final int bU = 42032;
    public static final int bV = 42033;
    public static final int bW = 42034;
    public static final int bX = 42035;
    public static final int bY = 42036;
    public static final int bZ = 42037;
    public static final int ba = 37391;
    public static final int bb = 37393;
    public static final int bc = 37394;
    public static final int bd = 37395;
    public static final int be = 37396;
    public static final int bf = 37397;
    public static final int bg = 37398;
    public static final int bh = 37500;
    public static final int bi = 37510;
    public static final int bj = 37520;
    public static final int bk = 37521;
    public static final int bl = 37522;
    public static final int bm = 40091;
    public static final int bn = 40092;
    public static final int bo = 40093;
    public static final int bp = 40094;
    public static final int bq = 40095;
    public static final int br = 40960;
    public static final int bs = 40961;
    public static final int bt = 40962;
    public static final int bu = 40963;
    public static final int bv = 40964;
    public static final int bw = 41483;
    public static final int bx = 41484;
    public static final int by = 41486;
    public static final int bz = 41487;
    public static final int ca = 42240;
    public static final int cb = 50341;
    public static final int cc = 50898;
    public static final int cd = 50899;
    public static final int ce = 59932;
    public static final int cf = 65002;
    public static final int e = 1;
    public static final int f = 2;
    public static final int g = 254;
    public static final int h = 255;
    public static final int i = 256;
    public static final int j = 257;
    public static final int k = 258;
    public static final int l = 259;
    public static final int m = 262;
    public static final int n = 263;
    public static final int o = 266;
    public static final int p = 269;
    public static final int q = 270;
    public static final int r = 271;
    public static final int s = 272;
    public static final int t = 273;
    public static final int u = 274;
    public static final int v = 277;
    public static final int w = 278;
    public static final int x = 279;
    public static final int y = 280;
    public static final int z = 281;

    protected static void a(HashMap<Integer, String> hashMap) {
        hashMap.put(1, "Interoperability Index");
        hashMap.put(2, "Interoperability Version");
        hashMap.put(Integer.valueOf(g), "New Subfile Type");
        hashMap.put(255, "Subfile Type");
        hashMap.put(256, "Image Width");
        hashMap.put(257, "Image Height");
        hashMap.put(258, "Bits Per Sample");
        hashMap.put(259, ExifInterface.TAG_COMPRESSION);
        hashMap.put(262, "Photometric Interpretation");
        hashMap.put(263, "Thresholding");
        hashMap.put(266, "Fill Order");
        hashMap.put(269, "Document Name");
        hashMap.put(270, "Image Description");
        hashMap.put(271, ExifInterface.TAG_MAKE);
        hashMap.put(272, ExifInterface.TAG_MODEL);
        hashMap.put(273, "Strip Offsets");
        hashMap.put(274, ExifInterface.TAG_ORIENTATION);
        hashMap.put(277, "Samples Per Pixel");
        hashMap.put(278, "Rows Per Strip");
        hashMap.put(279, "Strip Byte Counts");
        hashMap.put(280, "Minimum Sample Value");
        hashMap.put(281, "Maximum Sample Value");
        hashMap.put(282, "X Resolution");
        hashMap.put(283, "Y Resolution");
        hashMap.put(284, "Planar Configuration");
        hashMap.put(285, "Page Name");
        hashMap.put(296, "Resolution Unit");
        hashMap.put(Integer.valueOf(F), "Page Number");
        hashMap.put(301, "Transfer Function");
        hashMap.put(305, ExifInterface.TAG_SOFTWARE);
        hashMap.put(306, "Date/Time");
        hashMap.put(Integer.valueOf(J), ExifInterface.TAG_ARTIST);
        hashMap.put(Integer.valueOf(L), "Predictor");
        hashMap.put(316, "Host Computer");
        hashMap.put(318, "White Point");
        hashMap.put(319, "Primary Chromaticities");
        hashMap.put(322, "Tile Width");
        hashMap.put(323, "Tile Length");
        hashMap.put(Integer.valueOf(Q), "Tile Offsets");
        hashMap.put(325, "Tile Byte Counts");
        hashMap.put(330, "Sub IFD Pointer(s)");
        hashMap.put(Integer.valueOf(T), "Transfer Range");
        hashMap.put(Integer.valueOf(U), "JPEG Tables");
        hashMap.put(512, "JPEG Proc");
        hashMap.put(515, "JPEG Restart Interval");
        hashMap.put(517, "JPEG Lossless Predictors");
        hashMap.put(518, "JPEG Point Transforms");
        hashMap.put(519, "JPEGQ Tables");
        hashMap.put(520, "JPEGDC Tables");
        hashMap.put(521, "JPEGAC Tables");
        hashMap.put(529, "YCbCr Coefficients");
        hashMap.put(530, "YCbCr Sub-Sampling");
        hashMap.put(531, "YCbCr Positioning");
        hashMap.put(532, "Reference Black/White");
        hashMap.put(559, "Strip Row Counts");
        hashMap.put(700, "Application Notes");
        hashMap.put(4096, "Related Image File Format");
        hashMap.put(4097, "Related Image Width");
        hashMap.put(4098, "Related Image Height");
        hashMap.put(Integer.valueOf(al), "Rating");
        hashMap.put(Integer.valueOf(am), "CFA Repeat Pattern Dim");
        hashMap.put(Integer.valueOf(an), "CFA Pattern");
        hashMap.put(Integer.valueOf(ao), "Battery Level");
        hashMap.put(Integer.valueOf(ap), ExifInterface.TAG_COPYRIGHT);
        hashMap.put(Integer.valueOf(aq), "Exposure Time");
        hashMap.put(Integer.valueOf(ar), "F-Number");
        hashMap.put(Integer.valueOf(as), "IPTC/NAA");
        hashMap.put(Integer.valueOf(at), "Inter Color Profile");
        hashMap.put(Integer.valueOf(au), "Exposure Program");
        hashMap.put(Integer.valueOf(av), "Spectral Sensitivity");
        hashMap.put(Integer.valueOf(aw), "ISO Speed Ratings");
        hashMap.put(Integer.valueOf(ax), "Opto-electric Conversion Function (OECF)");
        hashMap.put(Integer.valueOf(ay), "Interlace");
        hashMap.put(34858, "Time Zone Offset");
        hashMap.put(34859, "Self Timer Mode");
        hashMap.put(Integer.valueOf(aB), "Sensitivity Type");
        hashMap.put(Integer.valueOf(aC), "Standard Output Sensitivity");
        hashMap.put(Integer.valueOf(aD), "Recommended Exposure Index");
        hashMap.put(34858, "Time Zone Offset");
        hashMap.put(34859, "Self Timer Mode");
        hashMap.put(36864, "Exif Version");
        hashMap.put(Integer.valueOf(aH), "Date/Time Original");
        hashMap.put(Integer.valueOf(aI), "Date/Time Digitized");
        hashMap.put(37121, "Components Configuration");
        hashMap.put(Integer.valueOf(aK), "Compressed Bits Per Pixel");
        hashMap.put(Integer.valueOf(aL), "Shutter Speed Value");
        hashMap.put(Integer.valueOf(aM), "Aperture Value");
        hashMap.put(Integer.valueOf(aN), "Brightness Value");
        hashMap.put(Integer.valueOf(aO), "Exposure Bias Value");
        hashMap.put(Integer.valueOf(aP), "Max Aperture Value");
        hashMap.put(Integer.valueOf(aQ), "Subject Distance");
        hashMap.put(Integer.valueOf(aR), "Metering Mode");
        hashMap.put(37384, "White Balance");
        hashMap.put(Integer.valueOf(aU), ExifInterface.TAG_FLASH);
        hashMap.put(Integer.valueOf(aV), "Focal Length");
        hashMap.put(Integer.valueOf(aW), "Flash Energy");
        hashMap.put(Integer.valueOf(aX), "Spatial Frequency Response");
        hashMap.put(Integer.valueOf(aY), "Noise");
        hashMap.put(Integer.valueOf(aZ), "Focal Plane X Resolution");
        hashMap.put(Integer.valueOf(ba), "Focal Plane Y Resolution");
        hashMap.put(Integer.valueOf(bb), "Image Number");
        hashMap.put(Integer.valueOf(bc), "Security Classification");
        hashMap.put(Integer.valueOf(bd), "Image History");
        hashMap.put(Integer.valueOf(be), "Subject Location");
        hashMap.put(Integer.valueOf(bf), "Exposure Index");
        hashMap.put(Integer.valueOf(bg), "TIFF/EP Standard ID");
        hashMap.put(Integer.valueOf(bh), "Makernote");
        hashMap.put(Integer.valueOf(bi), "User Comment");
        hashMap.put(Integer.valueOf(bj), "Sub-Sec Time");
        hashMap.put(Integer.valueOf(bk), "Sub-Sec Time Original");
        hashMap.put(Integer.valueOf(bl), "Sub-Sec Time Digitized");
        hashMap.put(Integer.valueOf(bm), "Windows XP Title");
        hashMap.put(Integer.valueOf(bn), "Windows XP Comment");
        hashMap.put(Integer.valueOf(bo), "Windows XP Author");
        hashMap.put(Integer.valueOf(bp), "Windows XP Keywords");
        hashMap.put(Integer.valueOf(bq), "Windows XP Subject");
        hashMap.put(40960, "FlashPix Version");
        hashMap.put(40961, "Color Space");
        hashMap.put(Integer.valueOf(bt), "Exif Image Width");
        hashMap.put(Integer.valueOf(bu), "Exif Image Height");
        hashMap.put(Integer.valueOf(bv), "Related Sound File");
        hashMap.put(Integer.valueOf(bw), "Flash Energy");
        hashMap.put(Integer.valueOf(bx), "Spatial Frequency Response");
        hashMap.put(Integer.valueOf(by), "Focal Plane X Resolution");
        hashMap.put(Integer.valueOf(bz), "Focal Plane Y Resolution");
        hashMap.put(Integer.valueOf(bA), "Focal Plane Resolution Unit");
        hashMap.put(Integer.valueOf(bB), "Subject Location");
        hashMap.put(Integer.valueOf(bC), "Exposure Index");
        hashMap.put(Integer.valueOf(bD), "Sensing Method");
        hashMap.put(Integer.valueOf(bE), "File Source");
        hashMap.put(Integer.valueOf(bF), "Scene Type");
        hashMap.put(Integer.valueOf(bG), "CFA Pattern");
        hashMap.put(Integer.valueOf(bH), "Custom Rendered");
        hashMap.put(Integer.valueOf(bI), "Exposure Mode");
        hashMap.put(Integer.valueOf(bJ), "White Balance Mode");
        hashMap.put(Integer.valueOf(bK), "Digital Zoom Ratio");
        hashMap.put(Integer.valueOf(bL), "Focal Length 35");
        hashMap.put(Integer.valueOf(bM), "Scene Capture Type");
        hashMap.put(Integer.valueOf(bN), "Gain Control");
        hashMap.put(Integer.valueOf(bO), ExifInterface.TAG_CONTRAST);
        hashMap.put(Integer.valueOf(bP), ExifInterface.TAG_SATURATION);
        hashMap.put(Integer.valueOf(bQ), ExifInterface.TAG_SHARPNESS);
        hashMap.put(Integer.valueOf(bR), "Device Setting Description");
        hashMap.put(Integer.valueOf(bS), "Subject Distance Range");
        hashMap.put(Integer.valueOf(bT), "Unique Image ID");
        hashMap.put(Integer.valueOf(bU), "Camera Owner Name");
        hashMap.put(Integer.valueOf(bV), "Body Serial Number");
        hashMap.put(Integer.valueOf(bW), "Lens Specification");
        hashMap.put(Integer.valueOf(bX), "Lens Make");
        hashMap.put(Integer.valueOf(bY), "Lens Model");
        hashMap.put(Integer.valueOf(bZ), "Lens Serial Number");
        hashMap.put(Integer.valueOf(ca), ExifInterface.TAG_GAMMA);
        hashMap.put(Integer.valueOf(cb), "Print Image Matching (PIM) Info");
        hashMap.put(Integer.valueOf(cc), "Panasonic Title");
        hashMap.put(Integer.valueOf(cd), "Panasonic Title (2)");
        hashMap.put(Integer.valueOf(ce), "Padding");
        hashMap.put(Integer.valueOf(cf), "Lens");
    }
}
