package android.support.constraint;

public final class R {
    private R() {
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets = 2130772220;
        public static final int barrierDirection = 2130772221;
        public static final int chainUseRtl = 2130772327;
        public static final int constraintSet = 2130772429;
        public static final int constraint_referenced_ids = 2130772430;
        public static final int content = 2130772431;
        public static final int emptyVisibility = 2130772523;
        public static final int layout_constrainedHeight = 2130772898;
        public static final int layout_constrainedWidth = 2130772899;
        public static final int layout_constraintBaseline_creator = 2130772900;
        public static final int layout_constraintBaseline_toBaselineOf = 2130772901;
        public static final int layout_constraintBottom_creator = 2130772902;
        public static final int layout_constraintBottom_toBottomOf = 2130772903;
        public static final int layout_constraintBottom_toTopOf = 2130772904;
        public static final int layout_constraintCircle = 2130772905;
        public static final int layout_constraintCircleAngle = 2130772906;
        public static final int layout_constraintCircleRadius = 2130772907;
        public static final int layout_constraintDimensionRatio = 2130772908;
        public static final int layout_constraintEnd_toEndOf = 2130772909;
        public static final int layout_constraintEnd_toStartOf = 2130772910;
        public static final int layout_constraintGuide_begin = 2130772911;
        public static final int layout_constraintGuide_end = 2130772912;
        public static final int layout_constraintGuide_percent = 2130772913;
        public static final int layout_constraintHeight_default = 2130772914;
        public static final int layout_constraintHeight_max = 2130772915;
        public static final int layout_constraintHeight_min = 2130772916;
        public static final int layout_constraintHeight_percent = 2130772917;
        public static final int layout_constraintHorizontal_bias = 2130772918;
        public static final int layout_constraintHorizontal_chainStyle = 2130772919;
        public static final int layout_constraintHorizontal_weight = 2130772920;
        public static final int layout_constraintLeft_creator = 2130772921;
        public static final int layout_constraintLeft_toLeftOf = 2130772922;
        public static final int layout_constraintLeft_toRightOf = 2130772923;
        public static final int layout_constraintRight_creator = 2130772924;
        public static final int layout_constraintRight_toLeftOf = 2130772925;
        public static final int layout_constraintRight_toRightOf = 2130772926;
        public static final int layout_constraintStart_toEndOf = 2130772927;
        public static final int layout_constraintStart_toStartOf = 2130772928;
        public static final int layout_constraintTop_creator = 2130772929;
        public static final int layout_constraintTop_toBottomOf = 2130772930;
        public static final int layout_constraintTop_toTopOf = 2130772931;
        public static final int layout_constraintVertical_bias = 2130772932;
        public static final int layout_constraintVertical_chainStyle = 2130772933;
        public static final int layout_constraintVertical_weight = 2130772934;
        public static final int layout_constraintWidth_default = 2130772935;
        public static final int layout_constraintWidth_max = 2130772936;
        public static final int layout_constraintWidth_min = 2130772937;
        public static final int layout_constraintWidth_percent = 2130772938;
        public static final int layout_editor_absoluteX = 2130772940;
        public static final int layout_editor_absoluteY = 2130772941;
        public static final int layout_goneMarginBottom = 2130772942;
        public static final int layout_goneMarginEnd = 2130772943;
        public static final int layout_goneMarginLeft = 2130772944;
        public static final int layout_goneMarginRight = 2130772945;
        public static final int layout_goneMarginStart = 2130772946;
        public static final int layout_goneMarginTop = 2130772947;
        public static final int layout_optimizationLevel = 2130772950;

        private attr() {
        }
    }

    public static final class id {
        public static final int bottom = 2131427875;
        public static final int end = 2131429012;
        public static final int gone = 2131429484;
        public static final int invisible = 2131429902;
        public static final int left = 2131430401;
        public static final int packed = 2131431384;
        public static final int parent = 2131431411;
        public static final int percent = 2131431483;
        public static final int right = 2131431889;
        public static final int spread = 2131432588;
        public static final int spread_inside = 2131432589;
        public static final int start = 2131432602;
        public static final int top = 2131432993;
        public static final int wrap = 2131434016;

        private id() {
        }
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = {16842948, 16843039, 16843040, 16843071, 16843072, com.xiaomi.smarthome.R.attr.barrierAllowsGoneWidgets, com.xiaomi.smarthome.R.attr.barrierDirection, com.xiaomi.smarthome.R.attr.chainUseRtl, com.xiaomi.smarthome.R.attr.constraintSet, com.xiaomi.smarthome.R.attr.constraint_referenced_ids, com.xiaomi.smarthome.R.attr.layout_constrainedHeight, com.xiaomi.smarthome.R.attr.layout_constrainedWidth, com.xiaomi.smarthome.R.attr.layout_constraintBaseline_creator, com.xiaomi.smarthome.R.attr.layout_constraintBaseline_toBaselineOf, com.xiaomi.smarthome.R.attr.layout_constraintBottom_creator, com.xiaomi.smarthome.R.attr.layout_constraintBottom_toBottomOf, com.xiaomi.smarthome.R.attr.layout_constraintBottom_toTopOf, com.xiaomi.smarthome.R.attr.layout_constraintCircle, com.xiaomi.smarthome.R.attr.layout_constraintCircleAngle, com.xiaomi.smarthome.R.attr.layout_constraintCircleRadius, com.xiaomi.smarthome.R.attr.layout_constraintDimensionRatio, com.xiaomi.smarthome.R.attr.layout_constraintEnd_toEndOf, com.xiaomi.smarthome.R.attr.layout_constraintEnd_toStartOf, com.xiaomi.smarthome.R.attr.layout_constraintGuide_begin, com.xiaomi.smarthome.R.attr.layout_constraintGuide_end, com.xiaomi.smarthome.R.attr.layout_constraintGuide_percent, com.xiaomi.smarthome.R.attr.layout_constraintHeight_default, com.xiaomi.smarthome.R.attr.layout_constraintHeight_max, com.xiaomi.smarthome.R.attr.layout_constraintHeight_min, com.xiaomi.smarthome.R.attr.layout_constraintHeight_percent, com.xiaomi.smarthome.R.attr.layout_constraintHorizontal_bias, com.xiaomi.smarthome.R.attr.layout_constraintHorizontal_chainStyle, com.xiaomi.smarthome.R.attr.layout_constraintHorizontal_weight, com.xiaomi.smarthome.R.attr.layout_constraintLeft_creator, com.xiaomi.smarthome.R.attr.layout_constraintLeft_toLeftOf, com.xiaomi.smarthome.R.attr.layout_constraintLeft_toRightOf, com.xiaomi.smarthome.R.attr.layout_constraintRight_creator, com.xiaomi.smarthome.R.attr.layout_constraintRight_toLeftOf, com.xiaomi.smarthome.R.attr.layout_constraintRight_toRightOf, com.xiaomi.smarthome.R.attr.layout_constraintStart_toEndOf, com.xiaomi.smarthome.R.attr.layout_constraintStart_toStartOf, com.xiaomi.smarthome.R.attr.layout_constraintTop_creator, com.xiaomi.smarthome.R.attr.layout_constraintTop_toBottomOf, com.xiaomi.smarthome.R.attr.layout_constraintTop_toTopOf, com.xiaomi.smarthome.R.attr.layout_constraintVertical_bias, com.xiaomi.smarthome.R.attr.layout_constraintVertical_chainStyle, com.xiaomi.smarthome.R.attr.layout_constraintVertical_weight, com.xiaomi.smarthome.R.attr.layout_constraintWidth_default, com.xiaomi.smarthome.R.attr.layout_constraintWidth_max, com.xiaomi.smarthome.R.attr.layout_constraintWidth_min, com.xiaomi.smarthome.R.attr.layout_constraintWidth_percent, com.xiaomi.smarthome.R.attr.layout_editor_absoluteX, com.xiaomi.smarthome.R.attr.layout_editor_absoluteY, com.xiaomi.smarthome.R.attr.layout_goneMarginBottom, com.xiaomi.smarthome.R.attr.layout_goneMarginEnd, com.xiaomi.smarthome.R.attr.layout_goneMarginLeft, com.xiaomi.smarthome.R.attr.layout_goneMarginRight, com.xiaomi.smarthome.R.attr.layout_goneMarginStart, com.xiaomi.smarthome.R.attr.layout_goneMarginTop, com.xiaomi.smarthome.R.attr.layout_optimizationLevel};
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
        public static final int ConstraintLayout_Layout_barrierDirection = 6;
        public static final int ConstraintLayout_Layout_chainUseRtl = 7;
        public static final int ConstraintLayout_Layout_constraintSet = 8;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids = 9;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight = 10;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth = 11;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintCircle = 17;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 56;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 57;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 58;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 59;
        public static final int[] ConstraintLayout_placeholder = {com.xiaomi.smarthome.R.attr.content, com.xiaomi.smarthome.R.attr.emptyVisibility};
        public static final int ConstraintLayout_placeholder_content = 0;
        public static final int ConstraintLayout_placeholder_emptyVisibility = 1;
        public static final int[] ConstraintSet = {16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843039, 16843040, 16843071, 16843072, 16843551, 16843552, 16843553, 16843554, 16843555, 16843556, 16843557, 16843558, 16843559, 16843560, 16843701, 16843702, 16843770, 16843840, com.xiaomi.smarthome.R.attr.barrierAllowsGoneWidgets, com.xiaomi.smarthome.R.attr.barrierDirection, com.xiaomi.smarthome.R.attr.chainUseRtl, com.xiaomi.smarthome.R.attr.constraint_referenced_ids, com.xiaomi.smarthome.R.attr.layout_constrainedHeight, com.xiaomi.smarthome.R.attr.layout_constrainedWidth, com.xiaomi.smarthome.R.attr.layout_constraintBaseline_creator, com.xiaomi.smarthome.R.attr.layout_constraintBaseline_toBaselineOf, com.xiaomi.smarthome.R.attr.layout_constraintBottom_creator, com.xiaomi.smarthome.R.attr.layout_constraintBottom_toBottomOf, com.xiaomi.smarthome.R.attr.layout_constraintBottom_toTopOf, com.xiaomi.smarthome.R.attr.layout_constraintCircle, com.xiaomi.smarthome.R.attr.layout_constraintCircleAngle, com.xiaomi.smarthome.R.attr.layout_constraintCircleRadius, com.xiaomi.smarthome.R.attr.layout_constraintDimensionRatio, com.xiaomi.smarthome.R.attr.layout_constraintEnd_toEndOf, com.xiaomi.smarthome.R.attr.layout_constraintEnd_toStartOf, com.xiaomi.smarthome.R.attr.layout_constraintGuide_begin, com.xiaomi.smarthome.R.attr.layout_constraintGuide_end, com.xiaomi.smarthome.R.attr.layout_constraintGuide_percent, com.xiaomi.smarthome.R.attr.layout_constraintHeight_default, com.xiaomi.smarthome.R.attr.layout_constraintHeight_max, com.xiaomi.smarthome.R.attr.layout_constraintHeight_min, com.xiaomi.smarthome.R.attr.layout_constraintHeight_percent, com.xiaomi.smarthome.R.attr.layout_constraintHorizontal_bias, com.xiaomi.smarthome.R.attr.layout_constraintHorizontal_chainStyle, com.xiaomi.smarthome.R.attr.layout_constraintHorizontal_weight, com.xiaomi.smarthome.R.attr.layout_constraintLeft_creator, com.xiaomi.smarthome.R.attr.layout_constraintLeft_toLeftOf, com.xiaomi.smarthome.R.attr.layout_constraintLeft_toRightOf, com.xiaomi.smarthome.R.attr.layout_constraintRight_creator, com.xiaomi.smarthome.R.attr.layout_constraintRight_toLeftOf, com.xiaomi.smarthome.R.attr.layout_constraintRight_toRightOf, com.xiaomi.smarthome.R.attr.layout_constraintStart_toEndOf, com.xiaomi.smarthome.R.attr.layout_constraintStart_toStartOf, com.xiaomi.smarthome.R.attr.layout_constraintTop_creator, com.xiaomi.smarthome.R.attr.layout_constraintTop_toBottomOf, com.xiaomi.smarthome.R.attr.layout_constraintTop_toTopOf, com.xiaomi.smarthome.R.attr.layout_constraintVertical_bias, com.xiaomi.smarthome.R.attr.layout_constraintVertical_chainStyle, com.xiaomi.smarthome.R.attr.layout_constraintVertical_weight, com.xiaomi.smarthome.R.attr.layout_constraintWidth_default, com.xiaomi.smarthome.R.attr.layout_constraintWidth_max, com.xiaomi.smarthome.R.attr.layout_constraintWidth_min, com.xiaomi.smarthome.R.attr.layout_constraintWidth_percent, com.xiaomi.smarthome.R.attr.layout_editor_absoluteX, com.xiaomi.smarthome.R.attr.layout_editor_absoluteY, com.xiaomi.smarthome.R.attr.layout_goneMarginBottom, com.xiaomi.smarthome.R.attr.layout_goneMarginEnd, com.xiaomi.smarthome.R.attr.layout_goneMarginLeft, com.xiaomi.smarthome.R.attr.layout_goneMarginRight, com.xiaomi.smarthome.R.attr.layout_goneMarginStart, com.xiaomi.smarthome.R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_alpha = 13;
        public static final int ConstraintSet_android_elevation = 26;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 24;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 23;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_maxHeight = 10;
        public static final int ConstraintSet_android_maxWidth = 9;
        public static final int ConstraintSet_android_minHeight = 12;
        public static final int ConstraintSet_android_minWidth = 11;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotation = 20;
        public static final int ConstraintSet_android_rotationX = 21;
        public static final int ConstraintSet_android_rotationY = 22;
        public static final int ConstraintSet_android_scaleX = 18;
        public static final int ConstraintSet_android_scaleY = 19;
        public static final int ConstraintSet_android_transformPivotX = 14;
        public static final int ConstraintSet_android_transformPivotY = 15;
        public static final int ConstraintSet_android_translationX = 16;
        public static final int ConstraintSet_android_translationY = 17;
        public static final int ConstraintSet_android_translationZ = 25;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_barrierAllowsGoneWidgets = 27;
        public static final int ConstraintSet_barrierDirection = 28;
        public static final int ConstraintSet_chainUseRtl = 29;
        public static final int ConstraintSet_constraint_referenced_ids = 30;
        public static final int ConstraintSet_layout_constrainedHeight = 31;
        public static final int ConstraintSet_layout_constrainedWidth = 32;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 33;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 34;
        public static final int ConstraintSet_layout_constraintBottom_creator = 35;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 36;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 37;
        public static final int ConstraintSet_layout_constraintCircle = 38;
        public static final int ConstraintSet_layout_constraintCircleAngle = 39;
        public static final int ConstraintSet_layout_constraintCircleRadius = 40;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 41;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 42;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 43;
        public static final int ConstraintSet_layout_constraintGuide_begin = 44;
        public static final int ConstraintSet_layout_constraintGuide_end = 45;
        public static final int ConstraintSet_layout_constraintGuide_percent = 46;
        public static final int ConstraintSet_layout_constraintHeight_default = 47;
        public static final int ConstraintSet_layout_constraintHeight_max = 48;
        public static final int ConstraintSet_layout_constraintHeight_min = 49;
        public static final int ConstraintSet_layout_constraintHeight_percent = 50;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 51;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 52;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 53;
        public static final int ConstraintSet_layout_constraintLeft_creator = 54;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 55;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 56;
        public static final int ConstraintSet_layout_constraintRight_creator = 57;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 58;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 59;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 60;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 61;
        public static final int ConstraintSet_layout_constraintTop_creator = 62;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 63;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 64;
        public static final int ConstraintSet_layout_constraintVertical_bias = 65;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 66;
        public static final int ConstraintSet_layout_constraintVertical_weight = 67;
        public static final int ConstraintSet_layout_constraintWidth_default = 68;
        public static final int ConstraintSet_layout_constraintWidth_max = 69;
        public static final int ConstraintSet_layout_constraintWidth_min = 70;
        public static final int ConstraintSet_layout_constraintWidth_percent = 71;
        public static final int ConstraintSet_layout_editor_absoluteX = 72;
        public static final int ConstraintSet_layout_editor_absoluteY = 73;
        public static final int ConstraintSet_layout_goneMarginBottom = 74;
        public static final int ConstraintSet_layout_goneMarginEnd = 75;
        public static final int ConstraintSet_layout_goneMarginLeft = 76;
        public static final int ConstraintSet_layout_goneMarginRight = 77;
        public static final int ConstraintSet_layout_goneMarginStart = 78;
        public static final int ConstraintSet_layout_goneMarginTop = 79;
        public static final int[] LinearConstraintLayout = {16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;

        private styleable() {
        }
    }
}
