package org.apache.commons.compress.archivers.tar;

public interface TarConstants {
    public static final int A = 155;
    public static final int B = 12;
    public static final int C = 12;
    public static final int D = 12;
    public static final int E = 4;
    public static final int F = 1;
    public static final int G = 96;
    public static final int H = 1;
    public static final int I = 12;
    public static final int J = 504;
    public static final int K = 1;
    public static final byte L = 0;
    public static final byte M = 48;
    public static final byte N = 49;
    public static final byte O = 50;
    public static final byte P = 51;
    public static final byte Q = 52;
    public static final byte R = 53;
    public static final byte S = 54;
    public static final byte T = 55;
    public static final byte U = 75;
    public static final byte V = 76;
    public static final byte W = 83;
    public static final byte X = 120;
    public static final byte Y = 88;
    public static final byte Z = 103;

    /* renamed from: a  reason: collision with root package name */
    public static final int f3242a = 512;
    public static final String aa = "ustar\u0000";
    public static final String ab = "00";
    public static final String ac = "ustar ";
    public static final String ad = " \u0000";
    public static final String ae = "0\u0000";
    public static final String af = "ustar\u0000";
    public static final String ag = "\u0000\u0000";
    public static final String ah = "././@LongLink";
    public static final String ai = "tar\u0000";
    public static final int aj = 508;
    public static final int ak = 4;
    public static final int al = 131;
    public static final int am = 12;
    public static final int an = 12;
    public static final int f = 10240;
    public static final int g = 2;
    public static final int h = 3;
    public static final int i = 4;
    public static final int j = 100;
    public static final int k = 8;
    public static final int l = 8;
    public static final int m = 8;
    public static final long n = 2097151;
    public static final int o = 8;
    public static final int p = 148;
    public static final int q = 12;
    public static final long r = 8589934591L;
    public static final int s = 257;
    public static final int t = 6;
    public static final int u = 263;
    public static final int v = 2;
    public static final int w = 12;
    public static final int x = 32;
    public static final int y = 32;
    public static final int z = 8;
}
